[workspace]
resolver = "2"
members = [
    "examples/cube",
    "examples/gltf",
    "examples/scene-viewer",
    "rend3",
    "rend3-gltf",
    "rend3-pbr",
    "rend3-pbr-bake",
    "rend3-types"
]

[profile.release]
debug = true
lto = "thin"

[patch.crates-io]
# wgpu = { git = "https://github.com/gfx-rs/wgpu.git", rev = "938c069608213b209e420b9087deb983ef732433" }
# wgpu-types = { git = "https://github.com/gfx-rs/wgpu.git", rev = "938c069608213b209e420b9087deb983ef732433" }
# wgpu = { path = "../wgpu/wgpu" }
# wgpu-types = { path = "../wgpu/wgpu-types" }
